server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 3.132.233.240
     # redis 설정 필요

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.132.233.240:3306/blog?serverTimezone=Asia/Seoul
    username: admin
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create #최초에는 create로 만들지만 차후에는 update로 변경해야 함 , 당연히 mysql도 실행중이어야 함
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #entity를 만들 때 즉 테이블을 만들 때 변수 그대로 db에 만들어준다
      use-new-id-generator-mappings: false # jpa의 기본 넘버링 전략을 따라가지 않겠다
    show-sql: true
    properties:
      hibernate.format_sql: true # 정렬이 되어 콘솔창에 뜸

    jackson:
      serialization:
        fail-on-empty-beans: false


API-KEY:
  clientKey: 428545857802c4216b58954a115f7ad1
  callBackUri : http://3.132.233.240:8000/auth/kakao/callback
  tokenRequestUri : https://kauth.kakao.com/oauth/token
  profileRequestUri : https://kapi.kakao.com/v2/user/me

cos:
  key: cos1234
